version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: mpath_sql
    restart: always
    environment:
      SA_PASSWORD: "StrongPassword!2025"
      ACCEPT_EULA: "Y"
    ports:
      - "1400:1433"
    networks:
      - mpath_network

  backend:
    build:
      context: ./backend/mPathProject
      dockerfile: Dockerfile
    container_name: mpath_backend
    restart: always
    depends_on:
      - db
    environment:
      ConnectionStrings__Connection: "Server=db,1433;Database=mPathDB;User Id=sa;Password=StrongPassword!2025;TrustServerCertificate=True;"
      ASPNETCORE_ENVIRONMENT: "Production"
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - mpath_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mpath_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - mpath_network

networks:
  mpath_network:
    driver: bridge
