@mPathProject_HostAddress = https://localhost:7177

GET {{mPathProject_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{mPathProject_HostAddress}}/weatherforecast

###

GET {{mPathProject_HostAddress}}/api/doctor

###

GET {{mPathProject_HostAddress}}/api/doctor

###

GET {{mPathProject_HostAddress}}/api/doctor

###
