// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mPathProject.Context;

#nullable disable

namespace mPathProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250129012138_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("mPathProject.Models.Admission", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("admissionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("doctorId")
                        .HasColumnType("bigint");

                    b.Property<string>("observation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("patientId")
                        .HasColumnType("bigint");

                    b.Property<string>("patientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Admissions");

                    b.HasData(
                        new
                        {
                            id = 1L,
                            admissionDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            diagnosis = "Flu",
                            doctorId = 1L,
                            observation = "Mild symptoms",
                            patientId = 1L,
                            patientName = "Alice Johnson"
                        },
                        new
                        {
                            id = 2L,
                            admissionDate = new DateTime(2023, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            diagnosis = "Broken arm",
                            doctorId = 2L,
                            observation = "Needs surgery",
                            patientId = 2L,
                            patientName = "Bob Brown"
                        });
                });

            modelBuilder.Entity("mPathProject.Models.Discharge", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("admissionId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("dischargeDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("doctorId")
                        .HasColumnType("bigint");

                    b.Property<string>("doctorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("patientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("treatment")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id");

                    b.ToTable("Discharges");

                    b.HasData(
                        new
                        {
                            id = 1L,
                            admissionId = 1L,
                            amount = 100.00m,
                            dischargeDate = new DateTime(2023, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            doctorId = 1L,
                            doctorName = "John Doe",
                            patientName = "Alice Johnson",
                            treatment = "Antibiotics"
                        },
                        new
                        {
                            id = 2L,
                            admissionId = 2L,
                            amount = 500.00m,
                            dischargeDate = new DateTime(2023, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            doctorId = 2L,
                            doctorName = "Jane Smith",
                            patientName = "Bob Brown",
                            treatment = "Surgery"
                        });
                });

            modelBuilder.Entity("mPathProject.Models.Doctor", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            id = 1L,
                            active = true,
                            email = "john.doe@example.com",
                            firstName = "John",
                            lastName = "Doe"
                        },
                        new
                        {
                            id = 2L,
                            active = true,
                            email = "jane.smith@example.com",
                            firstName = "Jane",
                            lastName = "Smith"
                        });
                });

            modelBuilder.Entity("mPathProject.Models.Patient", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("observations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            id = 1L,
                            address = "123 Main St",
                            email = "alice.johnson@example.com",
                            firstName = "Alice",
                            lastName = "Johnson",
                            observations = "",
                            phoneNumber = "1234567890"
                        },
                        new
                        {
                            id = 2L,
                            address = "456 Elm St",
                            email = "bob.brown@example.com",
                            firstName = "Bob",
                            lastName = "Brown",
                            observations = "",
                            phoneNumber = "0987654321"
                        });
                });

            modelBuilder.Entity("mPathProject.Models.User", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("userRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            id = 1L,
                            email = "doctor@doctor.com",
                            password = "AQAAAAIAAYagAAAAEMPv0sp+FoVDuxBgcsym2p7fRtW3+em2g2W7wd0pgNFKwmXtkjCFcJIEyy2cmXK6pw==",
                            userRole = "Doctor"
                        },
                        new
                        {
                            id = 2L,
                            email = "admin@admin.com",
                            password = "AQAAAAIAAYagAAAAEHAgp0HFG9qc9eOr9W15Dp/qcrk3rbaCDo97hBui3SIlwim0ojzgn8lUQxBwEyWIaQ==",
                            userRole = "Admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
